# .streamlit/secrets.toml

# Cấu hình cho RAG Chatbot (n8n Webhook)
N8N_WEBHOOK_URL = "https://n8n.srv1002180.hstgr.cloud/webhook/Rag-KLTT"

# Cấu hình cho Chatbot Gemini (API Key)
GEMINI_API_KEY = "AIzaSyB8kzqnUMxTiBT6oG-rLHo38fbJh6XKyVc"
