
GEMINI_API_KEY = "AIzaSyB8kzqnUMxTiBT6oG-rLHo38fbJh6XKyVc"
GEMINI_MODEL   = "gemini-1.5-flash"  # hoặc gemini-1.5-pro
# Tùy chọn: prompt hệ thống cho bot
GEMINI_SYSTEM_PROMPT = "Bạn là trợ lý giúp phân tích kết luận thanh tra. Trả lời ngắn gọn, chính xác."
